config/routes.rb
Rails.application.routes.draw do
  resources :plains

end

app/models/plain.rb
class Plain < ActiveRecord::Base
  scope :where_like_tsukkomi_origin, ->(src_text) {
    text = src_text.gsub(/[\\%_]/){|m| "\\#{m}"}
    where("tsukkomi_origin LIKE ?", "%#{text}%") 
  }

  scope :where_like_tsukkomi_basic, ->(src_text) {
    text = src_text.gsub(/[\\%_]/){|m| "\\#{m}"}
    where("tsukkomi_basic LIKE ?", "%#{text}%") 
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plains_controller.rb
class PlainsController < ApplicationController
  before_action :set_plain, only: [:show, :edit, :update, :destroy]

  # GET /plains
  # GET /plains.json
  def index
    @plains = Plain.all
  end

  # GET /plains/1
  # GET /plains/1.json
  def show
  end

  # GET /plains/new
  def new
    @plain = Plain.new
  end

  # GET /plains/1/edit
  def edit
  end

  # POST /plains
  # POST /plains.json
  def create
    @plain = Plain.new(plain_params)

    respond_to do |format|
      if @plain.save
        format.html { redirect_to @plain, notice: 'Plain was successfully created.' }
        format.json { render :show, status: :created, location: @plain }
      else
        format.html { render :new }
        format.json { render json: @plain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plains/1
  # PATCH/PUT /plains/1.json
  def update
    respond_to do |format|
      if @plain.update(plain_params)
        format.html { redirect_to @plain, notice: 'Plain was successfully updated.' }
        format.json { render :show, status: :ok, location: @plain }
      else
        format.html { render :edit }
        format.json { render json: @plain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plains/1
  # DELETE /plains/1.json
  def destroy
    @plain.destroy
    respond_to do |format|
      format.html { redirect_to plains_url, notice: 'Plain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plain
      @plain = Plain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plain_params
      params.require(:plain).permit(:boke, :tsukkomi)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plains_helper.rb
module PlainsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Template</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plains/_form.html.slim
= form_for @plain do |f|
  - if @plain.errors.any?
    #error_explanation
      h2 = "#{pluralize(@plain.errors.count, "error")} prohibited this plain from being saved:"
      ul
        - @plain.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :boke
    = f.text_field :boke
  .field
    = f.label :tsukkomi
    = f.text_field :tsukkomi
  .actions = f.submit

app/views/plains/edit.html.slim
h1 Editing plain

== render 'form'

= link_to 'Show', @plain
'|
= link_to 'Back', plains_path

app/views/plains/index.html.slim
h1 Listing plains

table
  thead
    tr
      th Boke
      th Tsukkomi
      th
      th
      th

  tbody
    - @plains.each do |plain|
      tr
        td = plain.boke
        td = plain.tsukkomi
        td = link_to 'Show', plain
        td = link_to 'Edit', edit_plain_path(plain)
        td = link_to 'Destroy', plain, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Plain', new_plain_path

app/views/plains/new.html.slim
h1 New plain

== render 'form'

= link_to 'Back', plains_path

app/views/plains/show.html.slim
p#notice = notice

p
  strong Boke:
  = @plain.boke
p
  strong Tsukkomi:
  = @plain.tsukkomi

= link_to 'Edit', edit_plain_path(@plain)
'|
= link_to 'Back', plains_path